### ISSUE TITLE
Sedona fails on Databricks 16.2

### ISSUE THREAD

**Issue by danielsparing** [CartoDB/analytics-toolbox-core#547]
**Describe the bug**
Sedona (installed with Analytics Toolbox) calls mostly fail on Databricks DBR 16.2 (even when using Photon). Single-row example queries seem to work, but once it is multiple rows, it fails. Same code works on DBR 16.1.

**To Reproduce**
1. Databricks compute DBR 16.2 (non-ML), photon or no photon, single-node.
2. Run the query:

```sql
%sql
select
  sedona_st_astext(sedona_st_geomfromtext('POINT (1 2)'))
  -- this works, but...
```

```sql
%sql
with t as (
  select
    explode(array('POINT (1 2)', 'POINT (1 2)')) as wkt
)
select
  sedona_st_astext(sedona_st_geomfromtext(wkt))
from
  t
-- works on 16.1, fails on 16.2 (even on photon)
```

3. See error

```
java.lang.NoClassDefFoundError: org/json4s/JsonAST$JValue
```

**Expected behavior**
No error

**Additional context**
Works fine on 15.4 LTS and 16.0, 16.1.

**Comment by ernesmb** [comment]
hey, @danielsparing thanks a lot for reporting. 

We'll investigate this issue, and see if it's something we can fix in a later release.

Since the affected functionality is not part of this repository, it would be better that you get in touch with th! CARTO Support team at support@carto.com

Thanks!
